name: ✨ Feature Request
description: Request a feature to help improve Homarr!
title: '<title>'
labels: ['✨ Feature']
body:
  - type: markdown
    attributes:
      value: |
        > [!WARNING]  
        > If you want to request a feature for 1.0, please open it on the new [repository](https://github.com/homarr-labs/homarr/issues/new/choose).
  - type: textarea
    id: feature
    attributes:
      label: Description 
      description: Describe the feature you would like to see. Tell us how you imagine it and try to provide as much useful information as possible. **PLEASE** use images/screenshots, include details about X & Y when requesting changes like X & Y service does, make your description atleast 300 characters. Having an unclear issue with too little detail will result in your issue being marked as invalid and closed.
      placeholder: An outline of the feature you would like to see implemented, include as much detail as possible!
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is the development of this feature?
      options:
        - Low (Nice-to-have)
        - Medium (Would be very useful)
        - High (App breaking feature)
    validations:
      required: true
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: Before submitting, please ensure that
      options:
        - label: You are **NOT** using a version superior to v1. if that is the case, please fill this issue on the new repository. 
          required: true
